# Generated by Django 5.2.10 on 2026-01-09 21:56

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('codigo_control', models.IntegerField(blank=True, help_text='Código administrativo interno', null=True)),
                ('propietario', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('ingreso_anual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CredencialPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('INEI', 'INEI'), ('OSCE', 'OSCE'), ('SENSICO', 'SENSICO'), ('AFP', 'AFP NET'), ('SIS', 'SIS'), ('ESSALUD', 'Viva Essalud')], max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('clave', encrypted_model_fields.fields.EncryptedCharField()),
                ('url_acceso', models.URLField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaDetraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('dni_titular', models.CharField(blank=True, max_length=15, null=True)),
                ('clave', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_detraccion', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DatosTributarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_sol', models.CharField(blank=True, max_length=50)),
                ('clave_sol', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('regimen_tributario', models.CharField(blank=True, choices=[('RMT', 'Régimen Mype Tributario'), ('GENERAL', 'Régimen General'), ('ESPECIAL', 'Régimen Especial'), ('RUS', 'Nuevo RUS')], max_length=20)),
                ('regimen_laboral', models.CharField(blank=True, max_length=50)),
                ('fecha_acreditacion_remype', models.DateField(blank=True, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_tributarios', to='gestion.cliente')),
            ],
        ),
    ]
