# Generated by Django 5.2.10 on 2026-01-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_historialbaja'),
        ('gestion', '0004_historialestado'),
    ]

    operations = [
    ]
