# Generated by Django 5.2.10 on 2026-01-29 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_merge_0004_historialbaja_0004_historialestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial de Estado', 'verbose_name_plural': 'Historiales de Estados'},
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='tipo_evento',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('REACTIVACION', 'Reactivación'), ('BAJA', 'Baja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
