# Generated by Django 5.2.10 on 2026-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_historialestado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRegimenLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Régimen Laboral',
                'verbose_name_plural': 'Tipos de Régimen Laboral',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(blank=True, choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C'), ('N/T', 'N/T - No definido')], max_length=20, null=True),
        ),
    ]
