# Generated by Django 5.2.10 on 2026-01-12 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ruc', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('propietario', models.CharField(max_length=255)),
                ('dni_propietario', models.CharField(blank=True, max_length=8, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('codigo_control', models.IntegerField(blank=True, null=True)),
                ('regimen_tributario', models.CharField(choices=[('RMT', 'Régimen MYPE Tributario'), ('ESPECIAL', 'Régimen Especial'), ('RUS', 'Nuevo RUS'), ('GENERAL', 'Régimen General')], default='RMT', max_length=20)),
                ('tipo_empresa', models.CharField(choices=[('SAC', 'Sociedad Anónima Cerrada'), ('EIRL', 'Empresa Individual de Resp. Ltda.'), ('SRL', 'Sociedad Comercial de Resp. Ltda.'), ('SA', 'Sociedad Anónima'), ('PN', 'Persona Natural')], default='PN', max_length=20)),
                ('categoria', models.CharField(blank=True, choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], max_length=20, null=True)),
                ('regimen_laboral_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('regimen_laboral_fecha', models.DateField(blank=True, null=True)),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresos_anuales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('libros_societarios', models.IntegerField(default=0)),
                ('selectivo_consumo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.CharField(blank=True, max_length=50, null=True)),
                ('sol_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('sol_clave', models.CharField(blank=True, max_length=100, null=True)),
                ('detraccion_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('detraccion_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('detraccion_clave', models.CharField(blank=True, max_length=100, null=True)),
                ('inei_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('inei_clave', models.CharField(blank=True, max_length=100, null=True)),
                ('afp_net_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('afp_net_clave', models.CharField(blank=True, max_length=100, null=True)),
                ('viva_essalud_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('viva_essalud_clave', models.CharField(blank=True, max_length=100, null=True)),
                ('sis_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('sis_clave', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_osce', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_sencico', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='gestion.cliente')),
            ],
        ),
    ]
