# Generated by Django 5.2.10 on 2026-01-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
    ]
