# Generated by Django 6.0.1 on 2026-01-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cliente_fecha_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateTimeField(auto_now_add=True)),
                ('fecha_reactivacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reactivación')),
                ('razon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón de la Baja')),
                ('estado', models.CharField(choices=[('BAJA', 'En Baja'), ('REACTIVADO', 'Reactivado')], default='BAJA', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_bajas', to='gestion.cliente')),
                ('usuario_baja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Baja',
                'verbose_name_plural': 'Historiales de Bajas',
                'ordering': ['-fecha_baja'],
            },
        ),
    ]
