# Generated by Django 5.2.10 on 2026-01-26 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cliente_fecha_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('INGRESO', 'Ingreso Nuevo'), ('BAJA', 'Baja Temporal'), ('REACTIVACION', 'Reactivación'), ('BAJA_DEFINITIVA', 'Baja Definitiva')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='gestion.cliente')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
