# Generated by Django 5.2.11 on 2026-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_responsable_alter_cliente_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_reactivacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Reactivación'),
        ),
    ]
