# Generated by Django 5.2.11 on 2026-02-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_cliente_fecha_reactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='planilla',
            field=models.BooleanField(default=False, verbose_name='Planilla'),
        ),
    ]
