# Generated by Django 5.2.11 on 2026-02-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_cliente_planilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroSocietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro Societario',
                'verbose_name_plural': 'Libros Societarios',
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='libros_societarios',
        ),
        migrations.AddField(
            model_name='cliente',
            name='libros_societarios',
            field=models.ManyToManyField(blank=True, to='gestion.librosocietario'),
        ),
    ]
