# Generated by Django 5.2.11 on 2026-02-25 23:35

from django.db import migrations


def create_initial_societarios(apps, schema_editor):
    LibroSocietario = apps.get_model('gestion', 'LibroSocietario')
    libros = [
        "Libro de actas",
        "Matrícula de acciones",
        "Libro de directorio",
    ]
    for nombre in libros:
        LibroSocietario.objects.get_or_create(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_librosocietario_remove_cliente_libros_societarios_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_societarios),
    ]
