# Generated by Django 5.2.11 on 2026-03-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_initial_libros_societarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni_propietario',
        ),
        migrations.RemoveField(
            model_name='credenciales',
            name='sis_usuario',
        ),
    ]
