# Generated by Django 5.2.11 on 2026-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_cliente_dni_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultimo_digito_ruc',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
    ]
