# Generated by Django 5.2.11 on 2026-03-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_cliente_ultimo_digito_ruc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['ultimo_digito_ruc', '-ruc']},
        ),
    ]
