# Generated by Django 5.2.11 on 2026-03-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['ultimo_digito_ruc', 'ruc']},
        ),
    ]
