# Generated by Django 5.2.11 on 2026-03-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['ultimo_digito_ruc', 'ruc'], 'permissions': [('can_use_advanced_filters', 'Can use advanced client filters')]},
        ),
    ]
